### ISSUE TITLE
2.9.1 breaks the following component while 2.8.2 works

### ISSUE THREAD

**Issue by episodeyang** [reactjs/react-docgen#91]
=== how to reproduce ===

```shell
npm install react-docgen@2.9.1
```

now try to parse the following code:
```javascript
/*
 * Created by ge on 6/23/16.
 */
import React, {Component, PropTypes} from "react";

var {func, bool, string, oneOf} = PropTypes;

/**
 * description of the component
 */
export default class HappySandwichMaker extends Component {

  static propTypes = {
    /** Whether we add lattice */
    lattice: bool,
    /** Which kind of cheese? */
    cheese: oneOf(["PepperJack", "Swiss", "American"]).isRequired,
    /**
     * The protein we add into the sandwich.
     * For example:
     * - Teriyaki Chicken
     * - Phily-cheese Steak
     * - Tuna Salad
     * - Seafood Salad
     * - fake chicken patty (veg)
     * */
    protein: string.isRequired,
    /**
     * the bite event handler. Called when you bite into the sandwich
     */
    onBite: func
  };

  static defaultProps = {
    lattice: true
  };

  render() {
    var {children} = this.props;
    // console.log([children]);
    return (
      <div>
        <button style={{     }}>
          I am a giant red button (and I'm not flat)
        </button>
        <pre>
          {children}
        </pre>
      </div>
    );
  }
}


```

Now do:

```
import * as docgen from "react-docgen"
var findAllComponentDefinitions = require('react-docgen/dist/resolver/findAllComponentDefinitions');

console.log(docgen.parse(fileSouceFromAbove, findAllComponentDefinitions));
```

It gives the following message: 

[Object is not a function]

The same works with version 2.8.2.

**Comment by fkling** [comment]
Uh ok, will take a look. Thank you for the report!

**Comment by episodeyang** [comment]
Thanks! Here is the line where the error pops up:

<img width="671" alt="screenshot 2016-06-24 14 34 31" src="https://cloud.githubusercontent.com/assets/630490/16351212/d7b7bbac-3a18-11e6-9d7b-6dc09d5680cd.png">

**Comment by fkling** [comment]
So it says `resolver` is not a function? Or which line are you referring to?

**Comment by episodeyang** [comment]
Yes! but the resolver I'm passing in **is** defined. Let me update the usage.

**Comment by episodeyang** [comment]
Just updated the usage in the example. If you use the `findAllCompoentDefinitions` resolver it breaks.

**Comment by fkling** [comment]
Oh. That's because you are using `require` to load the resolver. `findAllComponentDefinitions` has a default export, which Babel exports with the `default` key. So you'd have to pass `findAllComponentDefinitions.default` instead.

However, the standard resolvers are also exported from the index file, so you could just do

```js
import * as docgen from "react-docgen"
console.log(docgen.parse(fileSouceFromAbove, docgen.resolver.findAllComponentDefinitions));
```

Does that solve the issue?

I think I also know why it worked before: 6a655bd613109c622900c8c7af81397db2347dcf updated from Babel5 to Babel6 which changed that behavior I was mentioning (exporting the default export with the key `default`).

**Comment by episodeyang** [comment]
Thanks @fkling for responding! I just setup a new webpack loader and it now works with this version. You can see that here I just used the default resolver so it is all good. 

[https://www.npmjs.com/package/react-docgen-loader](https://www.npmjs.com/package/react-docgen-loader)

Also, this loader is now used in this template 
[http://www.episodeyang.com/react-es6-template/](http://www.episodeyang.com/react-es6-template/)

:P

**Comment by episodeyang** [comment]
Here is a screenshot!
<img width="907" alt="screenshot 2016-06-26 13 42 50" src="https://cloud.githubusercontent.com/assets/630490/16364772/e976eb4c-3ba3-11e6-9fd9-b4e6deef49a4.png">

**Comment by fkling** [comment]
Nice, I like it :)
